### PR TITLE
Update UIAlertControllerExtensions Docs

### PR DESCRIPTION
**Pull request by SD10**
- I've read the contributing guidelines before submitting this PR

- I'd like some feedback on the styling of the Docs, I followed the template, so I want to make sure this is the direction we want to head before I continue working

Thoughts:
- I'm currently showing both ways of using initializers/method calls (with or without default values)
Do we want to show both or if not, which of the two?

- Also, do we want to include the types of the Parameters?

EDIT: Also, those initializers in the table of contents are very messy. I don't have any better suggestions though.

### CODE REVIEW

**Comment by omaralbeik** [comment]
@SD10 You're doing a great job, thank you!

everything is great, 2 points:

- addAction, addTextField titles should have all parameters (exactly as they are in code)
- default values for method parameters should be deleted in the table at top


examples:

## in table:
init(title: String, error: Error, defaultActionButtonTitle: String, tintColor: UIColor?)


## in title:
init(title: String = "Error", error: Error, defaultActionButtonTitle: String = "OK", tintColor: UIColor? = nil)

**Comment by SD10** [comment]
@omaralbeik I've updated the initializers in the table. I'm confused about your first point though.
Could you elaborate more or show me?

**Comment by omaralbeik** [comment]
@SD10 Sure, I updated the code, I think I should re-write the contribution guidelines for the docs, I feel it confusing sometimes too.

**Comment by SD10** [comment]
DUH, I see it now
So:
- 1. Include parameters for the methods/initializers in the table
- 2. Update my reference links to match the name of the method/init

**Comment by SD10** [comment]
@omaralbeik Ok I'll follow this format and continue working through UIKit Docs as I have spare time. Thanks for taking the time to review this.

**Comment by omaralbeik** [comment]
As usual, thank you for the great work @SD10 :)

**Pull request merged**
